site_name: Flogo gRPC IoT Telemetry Template
site_description: Build gRPC servers for IoT real-time telemetry data processing and anomaly detection using TIBCO Flogo

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site