apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mp-entry-flogo-graphql-apis
  title: Flogo GraphQL APIs Template
  description: Create GraphQL APIs using TIBCO Flogo with product information from multiple data sources and flexible query capabilities
  backstage.io/techdocs-ref: dir:.
  tibco.developer.hub/marketplace:
    isNew: true
    popularity: 8
    isMultiInstall: false
    imageURL: ""
    moreInfo:
      - text: Flogo Documentation
        url: https://docs.tibco.com/products/tibco-flogo-enterprise
        icon: docs
      - text: GraphQL Documentation
        url: https://graphql.org/learn/
        icon: docs
      - text: TIBCO Flogo Enterprise
        url: https://www.tibco.com/products/tibco-flogo
        icon: star
      - text: Source Repository
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/tree/main/flogo/sample-templates/graphql-apis
        icon: github
  tags:
    - devhub-marketplace
    - flogo
    - graphql
    - apis
    - microservices
    - tibco
    - lightweight
    - data-integration
    - recommended
spec:
  owner: tibco-templates
  type: service
  presentation:
    buttonLabels:
      createButtonText: Install
  parameters:
    - title: Accept the Marketplace Entry
      required:
        - accept
      properties:
        description:
          type: "null"
          description: |
            ## Install Flogo GraphQL APIs Template into your TIBCO Developer Hub

            **Description:** Create GraphQL APIs using TIBCO Flogo with flexible data querying from multiple sources including product catalogs, pricing, and inventory systems.

            **What You'll Get:** Complete Flogo application with GraphQL schema definition, query resolvers, and integration patterns for building scalable API services.

            Each item made available to you in the TIBCO® Developer Hub Marketplace is subject to its own individual license. This item is subject to the following [license](https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/LICENSE).

            **By accessing or using this item, you agree to assume full responsibility for its proper use and compliance with all applicable license terms.**
        accept:
          title: I Agree
          type: boolean
          default: false
  steps:
    - id: registerItem
      name: Installing Marketplace Entry...
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/flogo/marketplace-entries/catalog-info-flogo-graphql-apis.yaml

  output:
    links:
      - title: Open in catalog
        type: catalog
        icon: catalog
        entityRef: ${{ steps.registerItem.output.entityRef }}
      - title: Documents
        url: /docs?filters%5Buser%5D=all&limit=20
        icon: techdocs
      - icon: docs
        title: Open Flogo GraphQL APIs Guide
        url: /docs/default/System/flogo-graphql-apis-template
      - title: Back to Marketplace
        icon: dashboard
        url: /marketplace?filters%5Bkind%5D=template&filters%5Btags%5D=devhub-marketplace&limit=20