site_name: SonarQube BWCE Plugin
site_description: SonarQube server setup with TIBCO BusinessWorks Container Edition plugin for comprehensive code quality analysis

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site