site_name: ${{ values.name | dump }}
site_description: ${{ values.description | dump }}

nav:
  - Introduction: index.md
  {% if values.include_jenkins -%}
  - Jenkins Integration: jenkins-integration.md
  {% endif -%}
  {% if values.include_kubernetes -%}
  - Kubernetes Deployment: kubernetes-deployment.md
  {% endif -%}
  {% if values.include_governance -%}
  - Governance Tools: governance.md
  {% endif -%}
  - Configuration: configuration.md
  - Examples: examples.md

plugins:
  - techdocs-core