apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  links:
    - title: TIBCO Cloud Home
      url: https://cloud.tibco.com/
    - title: Documentation
      url: https://docs.tibco.com/products/tibco-businessworks-container-edition
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  type: service
  lifecycle: development
  owner: ${{ values.owner | dump }}