site_name: "BWCE EBX SAP DataSync"
site_description: "TIBCO BusinessWorks Container Edition template for data synchronization between EBX and SAP using BAPI integration"

nav:
  - Introduction: index.md

plugins:
  - techdocs-core