apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: flogo-activity-avroschematransform
  title: Avro Schema Transform Activity
  description: Transform Avro schemas to JSON Schema and XSD formats with intelligent processing
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/mpandav-tibco/tib-devhub-hackathon/tree/main/flogo/extensions/activity/schema-transform/avroschematransform
  tibco.developer.hub/marketplace:
    isNew: true
    popularity: 6
    isMultiInstall: true
    imageURL: ""
    moreInfo:
      - text: Source Repository
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/tree/main/flogo/extensions/activity/schema-transform/avroschematransform
        icon: github
      - text: Documentation
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/flogo/extensions/activity/schema-transform/avroschematransform/docs/index.md
        icon: docs
  tags:
    - devhub-marketplace
    - flogo
    - activity
spec:
  owner: tibco-flogo-team
  type: template
  presentation:
    buttonLabels:
      createButtonText: Install Avro Schema Transform Activity
  parameters:
    - title: Accept the Marketplace Entry
      properties:
        accept:
          title: Accept Terms
          description: |
            ## Avro Schema Transform Activity
            
            Transform Avro schemas to JSON Schema and XSD formats with intelligent processing
            
            By installing this extension, you agree to use it according to TIBCO's terms.
          type: boolean
          default: false
      required:
        - accept
