site_name: Avro Schema Transform Activity
site_description: Transform Avro schemas to JSON Schema and XSD formats with intelligent processing

nav:
  - Home: index.md

theme:
  name: material
  palette:
    primary: blue
    accent: blue

docs_dir: docs
site_dir: site

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true