site_name: Avro Schema Transform Activity
site_description: Transform Avro schemas to JSON Schema and XSD formats with intelligent processing

nav:nav:
  - Introduction: index.md  
plugins:plugins:
  - techdocs-core 

docs_dir: docs
site_dir: site


