site_name: Avro Schema Transform Activitysite_name: Avro Schema Transform Activity

site_description: Transform Avro schemas to JSON Schema and XSD formats with intelligent processingsite_description: Transform Avro schemas to JSON Schema and XSD formats with intelligent processing



nav:nav:

  - Introduction: index.md  - Introduction: index.md



plugins:plugins:

  - techdocs-core  - techdocs-core



docs_dir: docsdocs_dir: docs

site_dir: sitesite_dir: site

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true