site_name: Avro Schema Transform Activity
site_description: Transform Avro schemas to JSON Schema and XSD formats with intelligent processing

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true