apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  title: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - tibco
    - bwce  
    - monitoring
    - ${{ values.deployment_type }}
    - ${{ values.database_type }}
  links:
    {% if values.deployment_type == 'kubernetes' %}
    - url: http://bwce-monitoring-service.${{ values.name }}.svc.cluster.local
      title: BWCEMon Dashboard (Internal)
      icon: dashboard
    {% else %}
    - url: http://localhost:8080  
      title: BWCEMon Dashboard (Local)
      icon: dashboard
    {% endif %}
    - url: https://docs.tibco.com/pub/bwce/${{ values.bwce_mon_version }}/doc/html/Default.htm#bwce-app-monitoring/
      title: BWCEMon Documentation
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: tibco-bwce
  dependsOn:
    {% if values.database_type != 'h2' %}
    - resource:${{ values.database_type }}-database
    {% endif %}
    {% if values.deployment_type == 'kubernetes' %}
    - resource:kubernetes-cluster
    {% else %}
    - resource:docker-runtime
    {% endif %}