site_name: XML Filter Activity
site_description: Advanced XML parsing, filtering, and manipulation capabilities

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
