site_name: BWCE Basics Learning Guidesite_name: ${{ values.name | dump }}

site_description: Comprehensive learning guide for TIBCO BusinessWorks Container Edition fundamentals, featuring hands-on tutorials, sample applications, and practical exercises for developers new to BWCEsite_description: ${{ values.description | dump }}



nav:nav:

  - Introduction: index.md  - Introduction: index.md

  - Architecture Overview: architecture.md

plugins:  - Development Setup: development-setup.md

  - techdocs-core  - Creating Applications: creating-applications.md

  - Process Design: process-design.md

docs_dir: docs  - Configuration: configuration.md

site_dir: site  {% if values.include_sample_app -%}
  - Sample Application: sample-application.md
  {% endif -%}
  {% if values.include_exercises -%}
  - Hands-on Exercises: exercises.md
  {% endif -%}
  {% if values.include_docker_setup -%}
  - Docker Deployment: docker-deployment.md
  {% endif -%}
  {% if values.include_kubernetes_deploy -%}
  - Kubernetes Deployment: kubernetes-deployment.md
  {% endif -%}
  {% if values.include_monitoring -%}
  - Monitoring & Logging: monitoring.md
  {% endif -%}
  {% if values.include_best_practices -%}
  - Best Practices: best-practices.md
  {% endif -%}
  - Resources: resources.md

plugins:
  - techdocs-core