# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x07sensors\"k\n\nSensorData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x01\x12\x10\n\x08pressure\x18\x03 \x01(\x01\x12\x10\n\x08humidity\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"\x07\n\x05\x45mpty2K\n\rSensorService\x12:\n\x11SendTelemetryData\x12\x13.sensors.SensorData\x1a\x0e.sensors.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=25
  _globals['_SENSORDATA']._serialized_end=132
  _globals['_EMPTY']._serialized_start=134
  _globals['_EMPTY']._serialized_end=141
  _globals['_SENSORSERVICE']._serialized_start=143
  _globals['_SENSORSERVICE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
