site_name: "BWCE CDC Salesforce EBX"
site_description: "TIBCO BusinessWorks Container Edition template for CDC integration between Salesforce and EBX using Kafka"

nav:
  - Introduction: index.md

plugins:
  - techdocs-core