apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Product-Catalogue-OpenAPI
  description: The openapi product catalogue information
  tags:
    - store
    - rest
  links:
    - url: https://github.com/mpandav-tibco/dev-hub-templates/blob/mastart/templates/apis/
      title: GitHub Repo
      icon: github
    - url: https://github.com/mpandav-tibco/dev-hub-templates/blob/mastart/templates/apis/Soap-Example.wsdl
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: group:default/catalog-team
  definition:
    $text: ./skeleton/openapi-product-catalogue.json
