apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: flogo-trigger-mysql-binlog-listener
  title: MySQL Binlog Listener Trigger
  description: Real-time MySQL binary log monitoring for change data capture and event processing
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/mpandav-tibco/tib-devhub-hackathon/tree/main/flogo/extensions/trigger/mysql-binlog-listener
  tibco.developer.hub/marketplace:
    isNew: true
    popularity: 7
    isMultiInstall: true
    imageURL: ""
    moreInfo:
      - text: Source Repository
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/tree/main/flogo/extensions/trigger/mysql-binlog-listener
        icon: github
      - text: Documentation
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/flogo/extensions/trigger/mysql-binlog-listener/docs/index.md
        icon: docs
  tags:
    - devhub-marketplace
    - flogo
    - trigger
spec:
  owner: tibco-flogo-team
  type: template
  presentation:
    buttonLabels:
      createButtonText: Install MySQL Binlog Listener Trigger
  parameters:
    - title: Accept the Marketplace Entry
      properties:
        accept:
          title: Accept Terms
          description: |
            ## MySQL Binlog Listener Trigger
            
            Real-time MySQL binary log monitoring for change data capture and event processing
            
            By installing this extension, you agree to use it according to TIBCO's terms.
          type: boolean
          default: false
      required:
        - accept
