site_name: MySQL Binlog Listener Trigger
site_description: Real-time MySQL binary log monitoring for change data capture

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
