apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: bwce-devhub-templates-guide
  title: BWCE with DevHub Templates Guide
  description: Documentation template providing comprehensive know-how for integrating TIBCO BusinessWorks Container Edition with Developer Hub templates, including Jenkins CI/CD, Kubernetes deployment, and governance tools
  tags:
    - bwce
    - devhub
    - templates
    - documentation
    - guide
    - tutorial
    - jenkins
    - kubernetes
    - tibco
    - businessworks
    - know-how
spec:
  owner: tibco-templates
  type: documentation

  parameters:
    - title: Documentation Configuration
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Documentation Name
          type: string
          description: Name of your BWCE DevHub integration documentation
          ui:field: EntityNamePicker
          ui:help: 'This will be the title of your documentation project'
        description:
          title: Description  
          type: string
          description: Brief description of your BWCE DevHub integration scenario
          ui:help: 'Describe the specific use case or environment this documentation covers'
        owner:
          title: Owner
          type: string
          description: Owner of the documentation (team or individual)
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
        documentation_type:
          title: Documentation Style
          type: string
          description: Choose the style of documentation to generate
          default: developer-guide
          enum:
            - developer-guide
            - tutorial
            - reference
            - how-to
          enumNames:
            - 'Developer Guide (Comprehensive)'
            - 'Step-by-Step Tutorial'
            - 'Reference Documentation'
            - 'How-To Guide'

    - title: Documentation Content
      properties:
        include_jenkins:
          title: Include Jenkins CI/CD Guide
          type: boolean
          description: Include detailed documentation on Jenkins pipeline setup and configuration for BWCE
          default: true
          ui:help: 'Covers Jenkins installation, pipeline configuration, and BWCE build automation'
        include_kubernetes:
          title: Include Kubernetes Deployment Guide
          type: boolean
          description: Include comprehensive Kubernetes deployment documentation for BWCE applications
          default: true
          ui:help: 'Covers cluster setup, deployment manifests, and service configuration'
        include_governance:
          title: Include Governance and Security
          type: boolean
          description: Include documentation for SonarQube code quality and Trivy security scanning integration
          default: true
          ui:help: 'Covers quality gates, security scanning, and compliance workflows'
        include_images:
          title: Include Visual Diagrams
          type: boolean
          description: Include workflow diagrams, architecture images, and step-by-step screenshots
          default: true
          ui:help: 'Adds visual elements to make the documentation easier to follow'

  steps:
    - id: fetch
      name: Generate Documentation
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          documentation_type: ${{ parameters.documentation_type }}
          include_jenkins: ${{ parameters.include_jenkins }}
          include_kubernetes: ${{ parameters.include_kubernetes }}
          include_governance: ${{ parameters.include_governance }}
          include_images: ${{ parameters.include_images }}

  output:
    text:
      - title: Generated Documentation
        content: |
          Your BWCE DevHub Templates documentation has been generated successfully!
          
          ## What was created:
          - Comprehensive guide for BWCE integration with Developer Hub templates
          {% if values.include_jenkins %}
          - Jenkins CI/CD pipeline documentation and examples
          {% endif %}
          {% if values.include_kubernetes %}
          - Kubernetes deployment guides and manifests
          {% endif %}
          {% if values.include_governance %}
          - SonarQube and Trivy security scanning setup
          {% endif %}
          {% if values.include_images %}
          - Visual workflow diagrams and screenshots
          {% endif %}
          
          ## Next Steps:
          1. Review the generated documentation files
          2. Customize the content for your specific environment
          3. Share with your development team
          4. Follow the step-by-step guides to implement BWCE DevHub integration