apiVersion: scaffolder.backstage.io/v1beta3apiVersion: scaffolder.backstage.io/v1beta3apiVersion: scaffolder.backstage.io/v1beta3

kind: Template

metadata:kind: Templatekind: Template

  name: bwce-devhub-templates-guide

  title: BWCE with DevHub Templates Guidemetadata:metadata:

  description: Documentation template providing comprehensive know-how for integrating TIBCO BusinessWorks Container Edition with Developer Hub templates, including Jenkins CI/CD, Kubernetes deployment, and governance tools

  tags:  name: bwce-devhub-templates-guide  name: bwce-devhub-templates-guide

    - bwce

    - devhub  title: BWCE with DevHub Templates Guide  title: BWCE with DevHub Templates Guide

    - templates

    - documentation  description: Documentation template providing comprehensive know-how for integrating TIBCO BusinessWorks Container Edition with Developer Hub templates, including Jenkins CI/CD, Kubernetes deployment, and governance tools  description: Documentation template providing comprehensive know-how for integrating TIBCO BusinessWorks Container Edition with Developer Hub templates, including Jenkins CI/CD, Kubernetes deployment, and governance tools

    - guide

    - tutorial  tags:  tags:

    - jenkins

    - kubernetes    - bwce    - devhub-marketplace

    - tibco

    - businessworks    - devhub    - bwce

    - know-how

spec:    - templates    - devhub

  owner: tibco-templates

  type: documentation    - documentation    - templates



  parameters:    - guide    - documentation

    - title: Documentation Configuration

      required:    - tutorial    - guide

        - name

        - description    - jenkins    - tutorial

        - owner

      properties:    - kubernetes    - jenkins

        name:

          title: Name    - tibco    - kubernetes

          type: string

          description: Unique name for your documentation instance    - businessworks    - tibco

          ui:field: EntityNamePicker

          ui:autofocus: true    - know-how    - businessworks

          default: my-bwce-documentation

        description:spec:    - know-how

          title: Description

          type: string  owner: tibco-templates  tibco.developer.hub/marketplace:

          description: A description for your BWCE documentation

          default: BWCE DevHub integration documentation  type: documentation    isNew: true

        owner:

          title: Owner    popularity: 9

          type: string

          description: Owner of the documentation  parameters:    isMultiInstall: false

          ui:field: OwnerPicker

          ui:options:    - title: Documentation Configuration    imageURL: ""

            allowedKinds:

              - Group      required:    moreInfo:



    - title: Documentation Options        - name      - text: BWCE Documentation

      properties:

        documentation_type:        - description        url: https://docs.tibco.com/products/tibco-businessworks-container-edition

          title: Documentation Type

          description: Choose the type of documentation to generate        - owner        icon: docs

          type: string

          default: comprehensive      properties:      - text: TIBCO Developer Hub

          enum:

            - comprehensive        name:        url: https://docs.tibco.com/pub/platform-cp/1.10.0/doc/html/Default.htm#Subsystems/platform-devhub/User-Guide/TIBCO-Developer-Hub-Overview.htm

            - quickstart

            - advanced          title: Name        icon: docs

          enumNames:

            - 'Comprehensive Guide (All Sections)'          type: string      - text: Source Repository

            - 'Quick Start (Essential Steps Only)'

            - 'Advanced Topics (Deep Dive)'          description: Unique name for your documentation instance        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/tree/main/bwce/documentation/bwce-with-devhub-templates

        include_jenkins:

          title: Include Jenkins CI/CD Documentation          ui:field: EntityNamePicker        icon: github

          type: boolean

          default: true          ui:autofocus: truespec:

          ui:help: 'Includes Jenkins pipeline setup and automation guides'

        include_kubernetes:          default: my-bwce-documentation  owner: tibco-templates

          title: Include Kubernetes Deployment Documentation

          type: boolean        description:  type: documentation

          default: true

          ui:help: 'Includes Kubernetes deployment strategies and service mesh configuration'          title: Description

        include_governance:

          title: Include Governance and Security Documentation          type: string  parameters:

          type: boolean

          default: true          description: A description for your BWCE documentation    - title: Documentation Configuration

          ui:help: 'Includes template governance, security, and compliance guidelines'

        include_images:          default: BWCE DevHub integration documentation      required:

          title: Include Visual Diagrams and Screenshots

          type: boolean        owner:        - name

          default: true

          ui:help: 'Adds visual elements to make the documentation easier to follow'          title: Owner        - description



  steps:          type: string        - owner

    - id: fetch

      name: Generate Documentation          description: Owner of the documentation      properties:

      action: fetch:template

      input:          ui:field: OwnerPicker        name:

        url: ./skeleton

        values:          ui:options:          title: Documentation Name

          name: ${{ parameters.name }}

          description: ${{ parameters.description }}            allowedKinds:          type: string

          owner: ${{ parameters.owner }}

          documentation_type: ${{ parameters.documentation_type }}              - Group          description: Name of your BWCE DevHub integration documentation

          include_jenkins: ${{ parameters.include_jenkins }}

          include_kubernetes: ${{ parameters.include_kubernetes }}          ui:field: EntityNamePicker

          include_governance: ${{ parameters.include_governance }}

          include_images: ${{ parameters.include_images }}    - title: Documentation Options          ui:help: 'This will be the title of your documentation project'



  output:      properties:        description:

    text:

      - title: Generated Documentation        documentation_type:          title: Description  

        content: |

          Your BWCE DevHub Templates documentation has been generated successfully!          title: Documentation Type          type: string

          

          ## What was created:          description: Choose the type of documentation to generate          description: Brief description of your BWCE DevHub integration scenario

          - Comprehensive guide for BWCE integration with Developer Hub templates

          {% if values.include_jenkins %}          type: string          ui:help: 'Describe the specific use case or environment this documentation covers'

          - Jenkins CI/CD pipeline documentation and examples

          {% endif %}          default: comprehensive        owner:

          {% if values.include_kubernetes %}

          - Kubernetes deployment strategies and configurations          enum:          title: Owner

          {% endif %}

          {% if values.include_governance %}            - comprehensive          type: string

          - Template governance and security guidelines

          {% endif %}            - quickstart          description: Owner of the documentation (team or individual)

          

          ## Next Steps:            - advanced          ui:field: OwnerPicker

          1. Review the generated documentation

          2. Customize sections for your specific use case          enumNames:          ui:options:

          3. Add organization-specific examples and configurations

          4. Share with your development team            - 'Comprehensive Guide (All Sections)'            catalogFilter:

          

          The documentation includes step-by-step guides, code examples, and best practices for:            - 'Quick Start (Essential Steps Only)'              kind: [Group, User]

          - Creating BWCE templates in Developer Hub

          - Setting up CI/CD pipelines with Jenkins            - 'Advanced Topics (Deep Dive)'        documentation_type:

          - Deploying to Kubernetes environments

          - Implementing governance and security measures        include_jenkins:          title: Documentation Style

          title: Include Jenkins CI/CD Documentation          type: string

          type: boolean          description: Choose the style of documentation to generate

          default: true          default: developer-guide

          ui:help: 'Includes Jenkins pipeline setup and automation guides'          enum:

        include_kubernetes:            - developer-guide

          title: Include Kubernetes Deployment Documentation            - tutorial

          type: boolean            - reference

          default: true            - how-to

          ui:help: 'Includes Kubernetes deployment strategies and service mesh configuration'          enumNames:

        include_governance:            - 'Developer Guide (Comprehensive)'

          title: Include Governance and Security Documentation            - 'Step-by-Step Tutorial'

          type: boolean            - 'Reference Documentation'

          default: true            - 'How-To Guide'

          ui:help: 'Includes template governance, security, and compliance guidelines'

        include_images:    - title: Documentation Content

          title: Include Visual Diagrams and Screenshots      properties:

          type: boolean        include_jenkins:

          default: true          title: Include Jenkins CI/CD Guide

          ui:help: 'Adds visual elements to make the documentation easier to follow'          type: boolean

          description: Include detailed documentation on Jenkins pipeline setup and configuration for BWCE

  steps:          default: true

    - id: fetch          ui:help: 'Covers Jenkins installation, pipeline configuration, and BWCE build automation'

      name: Generate Documentation        include_kubernetes:

      action: fetch:template          title: Include Kubernetes Deployment Guide

      input:          type: boolean

        url: ./skeleton          description: Include comprehensive Kubernetes deployment documentation for BWCE applications

        values:          default: true

          name: ${{ parameters.name }}          ui:help: 'Covers cluster setup, deployment manifests, and service configuration'

          description: ${{ parameters.description }}        include_governance:

          owner: ${{ parameters.owner }}          title: Include Governance and Security

          documentation_type: ${{ parameters.documentation_type }}          type: boolean

          include_jenkins: ${{ parameters.include_jenkins }}          description: Include documentation for SonarQube code quality and Trivy security scanning integration

          include_kubernetes: ${{ parameters.include_kubernetes }}          default: true

          include_governance: ${{ parameters.include_governance }}          ui:help: 'Covers quality gates, security scanning, and compliance workflows'

          include_images: ${{ parameters.include_images }}        include_images:

          title: Include Visual Diagrams

  output:          type: boolean

    text:          description: Include workflow diagrams, architecture images, and step-by-step screenshots

      - title: Generated Documentation          default: true

        content: |          ui:help: 'Adds visual elements to make the documentation easier to follow'

          Your BWCE DevHub Templates documentation has been generated successfully!

            steps:

          ## What was created:    - id: fetch

          - Comprehensive guide for BWCE integration with Developer Hub templates      name: Generate Documentation

          {% if values.include_jenkins %}      action: fetch:template

          - Jenkins CI/CD pipeline documentation and examples      input:

          {% endif %}        url: ./skeleton

          {% if values.include_kubernetes %}        values:

          - Kubernetes deployment strategies and configurations          name: ${{ parameters.name }}

          {% endif %}          description: ${{ parameters.description }}

          {% if values.include_governance %}          owner: ${{ parameters.owner }}

          - Template governance and security guidelines          documentation_type: ${{ parameters.documentation_type }}

          {% endif %}          include_jenkins: ${{ parameters.include_jenkins }}

                    include_kubernetes: ${{ parameters.include_kubernetes }}

          ## Next Steps:          include_governance: ${{ parameters.include_governance }}

          1. Review the generated documentation          include_images: ${{ parameters.include_images }}

          2. Customize sections for your specific use case

          3. Add organization-specific examples and configurations  output:

          4. Share with your development team    text:

                - title: Generated Documentation

          The documentation includes step-by-step guides, code examples, and best practices for:        content: |

          - Creating BWCE templates in Developer Hub          Your BWCE DevHub Templates documentation has been generated successfully!

          - Setting up CI/CD pipelines with Jenkins          

          - Deploying to Kubernetes environments          ## What was created:

          - Implementing governance and security measures          - Comprehensive guide for BWCE integration with Developer Hub templates
          {% if values.include_jenkins %}
          - Jenkins CI/CD pipeline documentation and examples
          {% endif %}
          {% if values.include_kubernetes %}
          - Kubernetes deployment guides and manifests
          {% endif %}
          {% if values.include_governance %}
          - SonarQube and Trivy security scanning setup
          {% endif %}
          {% if values.include_images %}
          - Visual workflow diagrams and screenshots
          {% endif %}
          
          ## Next Steps:
          1. Review the generated documentation files
          2. Customize the content for your specific environment
          3. Share with your development team
          4. Follow the step-by-step guides to implement BWCE DevHub integration