apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: bwce-devhub-templates-guide
  title: BWCE with DevHub Templates Guide
  description: Documentation template for BWCE DevHub integration
  tags:
    - bwce
    - devhub
    - documentation
spec:
  owner: tibco-templates
  type: documentation
  parameters:
    - title: Documentation Info
      required:
        - name
      properties:
        name:
          title: Documentation Name
          type: string
          default: bwce-documentation
  steps:
    - id: fetch
      name: Generate Documentation
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
  output:
    text:
      - title: Success
        content: Documentation created successfully!
