site_name: Template Engine Activity
site_description: Dynamic content generation and template processing capabilities

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site
