apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  tags:
    - bwce
    - devhub
    - documentation
    {% if values.include_jenkins %}- jenkins{% endif %}
    {% if values.include_kubernetes %}- kubernetes{% endif %}
    {% if values.include_governance %}- governance{% endif %}
  annotations:
    github.com/project-slug: ${{ values.destination.owner + "/" + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{ values.name }}
  links:
    - title: TIBCO BusinessWorks
      url: https://www.tibco.com/products/tibco-businessworks
      icon: star
    {% if values.include_jenkins %}
    - title: Jenkins Dashboard
      url: http://localhost:8080
      icon: build
    {% endif %}
    {% if values.include_kubernetes %}
    - title: Kubernetes Dashboard
      url: https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/
      icon: dashboard
    {% endif %}
spec:
  type: documentation
  lifecycle: development
  owner: ${{ values.owner | dump }}