site_name: PostgreSQL Listener Trigger
site_description: Real-time PostgreSQL NOTIFY/LISTEN event monitoring with SSL/TLS support

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
