site_name: PostgreSQL Listener Trigger
site_description: Real-time PostgreSQL NOTIFY/LISTEN event monitoring

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site
