apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mp-entry-flogo-trigger-postgreslistener
  title: PostgreSQL Listener Trigger
  description: Real-time PostgreSQL NOTIFY/LISTEN event monitoring with SSL/TLS support
  annotations:
    backstage.io/techdocs-ref: dir:.
  tibco.developer.hub/marketplace:
    isNew: true
    popularity: 7
    isMultiInstall: true
    imageURL: "https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/img/flogo-custom-activities.png"
    moreInfo:
      - text: Source Repository
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/tree/main/flogo/extensions/trigger/postgreslistener
        icon: github
      - text: Documentation
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/flogo/extensions/trigger/postgreslistener/docs/index.md
        icon: docs
  tags:
    - devhub-marketplace
    - flogo
    - trigger
spec:
  owner: tibco-flogo-team
  type: Flogo-Custom-Extension
  presentation:
    buttonLabels:
      createButtonText: Install PostgreSQL Listener Trigger
  parameters:
    - title: Accept the Marketplace Entry
      required:
        - accept
      properties:
        description:
          type: "null"
          description: |
            ## Install PostgreSQL Listener Trigger into your TIBCO Developer Hub

            **Description:** Real-time PostgreSQL NOTIFY/LISTEN event monitoring with SSL/TLS support

            **What You'll Get:** This Flogo extension will be added to your Developer Hub catalog for use in your applications.

            Each item made available to you in the TIBCO® Developer Hub Marketplace is subject to its own individual license. This item is subject to the following [license](https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/LICENSE).

            **By accessing or using this item, you agree to assume full responsibility for its proper use and compliance with all applicable license terms.**
        accept:
          title: I Agree
          type: boolean
          default: false
  steps:
    - id: registerItem
      name: Installing Marketplace Entry...
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/flogo/extensions/trigger/postgreslistener/catalog-info.yaml

  output:
    links:
      - title: Open in catalog
        type: catalog
        icon: catalog
        entityRef: ${{ steps.registerItem.output.entityRef }}
      - title: Documentation
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/flogo/extensions/trigger/postgreslistener/docs/index.md
        icon: docs
      - title: Back to Marketplace
        icon: dashboard
        url: /marketplace
