site_name: RPA Integration Template
site_description: Create RPA (Robotic Process Automation) integration solutions using TIBCO Flogo with UiPath workflow automation

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site