site_name: JSON Schema Transform Activity
site_description: Transform and validate JSON schemas with comprehensive processing

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
