site_name: JSON Schema Transform Activity
site_description: Transform and validate JSON schemas with intelligent processing

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site
