site_name: JSON Schema Transform Activity
site_description: Transform JSON Schema to XSD and Avro formats with constraint mapping

nav:
  - Home: index.md

theme:
  name: material
  palette:
    primary: blue
    accent: blue

docs_dir: docs
site_dir: site

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true