site_name: Write Log Activity
site_description: Enterprise logging with OpenTelemetry integration and ECS compliance

nav:
  - Home: index.md

theme:
  name: material
  palette:
    primary: blue
    accent: blue

docs_dir: docs
site_dir: site

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true