site_name: Write Log Activity
site_description: Enhanced logging capabilities with custom formatting and output options

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site
