site_name: XSD Schema Transform Activity
site_description: Transform and validate XSD schemas with intelligent processing

nav:nav:

  - Introduction: index.md 

plugins:plugins:

  - techdocs-core 

docs_dir: docs

site_dir: site
