site_name: XSD Schema Transform Activitysite_name: XSD Schema Transform Activity

site_description: Transform and validate XSD schemas with intelligent processingsite_description: Transform and validate XSD schemas with intelligent processing



nav:nav:

  - Introduction: index.md  - Introduction: index.md



plugins:plugins:

  - techdocs-core  - techdocs-core



docs_dir: docsdocs_dir: docs

site_dir: sitesite_dir: sitechema Transform Activity
site_description: Transform and validate XSD schemas with intelligent processing

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
