apiVersion: v1
kind: MarketplaceEntry
metadata:
  name: flogo-activity-xsdschematransform
  title: XSD Schema Transform Activity
  description: Transform XSD schemas to JSON Schema and Avro Schema formats with comprehensive configuration and namespace handling
  tags:
    - flogo
    - activity
    - xsd
    - schema-transform
    - json-schema
    - avro-schema
    - xml
    - data-modeling
spec:
  type: flogo-activity
  category: Data Processing
  author: TIBCO Flogo Team
  version: "1.0.0"
  license: Apache-2.0
  
  summary: |
    Comprehensive XSD schema transformation engine supporting conversion to JSON Schema and Avro formats. 
    Features extensive configuration options, namespace management, and intelligent handling of complex XSD constructs.

  features:
    - Complete XSD to JSON Schema conversion with multiple specification versions
    - Full XSD to Avro Schema transformation with logical types support
    - Flexible output formats (JSON Schema only, Avro only, or both)
    - Advanced namespace handling with multiple strategies
    - Complex type processing with inline, definitions, or reference modes
    - XML attribute inclusion and preservation options
    - Choice and union handling with configurable strategies
    - Input validation with detailed error reporting
    - Conversion statistics and performance metrics
    - Example value generation from XSD annotations

  useCases:
    - API schema migration from XML to JSON-based systems
    - Data pipeline schema standardization across formats
    - Microservices schema compatibility and transformation
    - Enterprise data integration with multi-format support
    - Schema registry population and management
    - Data modeling and architecture documentation
    - Legacy XML system modernization
    - Cross-platform data exchange format conversion

  inputs:
    xsdString:
      description: XSD schema string to transform
      type: string
      required: true
    outputFormat:
      description: Output format (jsonschema, avro, or both)
      type: string
      required: false
      default: "both"
    validateInput:
      description: Validate XSD schema before conversion
      type: boolean
      required: false
      default: false
    jsonSchemaVersion:
      description: JSON Schema version (draft-04, draft-07, 2019-09, 2020-12)
      type: string
      required: false
      default: "2020-12"
    avroNamespace:
      description: Namespace for Avro schema
      type: string
      required: false
      default: "com.example"
    includeAttributes:
      description: Include XML attributes in conversion
      type: boolean
      required: false
      default: true
    namespaceHandling:
      description: Namespace handling strategy (ignore, prefix, separate)
      type: string
      required: false
      default: "ignore"

  outputs:
    jsonSchemaString:
      description: Generated JSON Schema string
      type: string
    avroSchemaString:
      description: Generated Avro Schema string
      type: string
    validationResult:
      description: XSD validation result as JSON string
      type: string
    conversionStats:
      description: Conversion statistics as JSON string
      type: string
    error:
      description: Whether an error occurred during conversion
      type: boolean
    errorMessage:
      description: Error message if error occurred
      type: string

  documentation:
    readme: README.md
    examples: example/
    
  repository:
    type: git
    url: https://github.com/TIBCOSoftware/tib-devhub-hackathon
    directory: flogo/extensions/activity/schema-transform/xsdschematransform

  template:
    scaffoldUrl: ./template.yaml
    
  compatibility:
    flogoVersion: ">=1.0.0"
    goVersion: ">=1.16"
    formats: ["XSD", "JSON Schema", "Avro Schema"]