apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: flogo-activity-xsdschematransform
  title: XSD Schema Transform Flogo Activity
  description: Create a Flogo activity for transforming XSD schemas to JSON Schema and Avro Schema formats
  tags:
    - flogo
    - activity
    - xsd
    - schema-transform
    - json-schema
    - avro-schema
    - xml
spec:
  owner: tibco-flogo
  type: library
  parameters:
    - title: Repository Information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Component Name
          type: string
          description: Name of the XSD schema transform activity component
          pattern: '^[a-zA-Z0-9\-_]+$'
          default: "my-flogo-xsdschematransform-activity"
        description:
          title: Description
          type: string
          description: Description of your XSD schema transform activity implementation
          default: "Flogo activity for transforming XSD schemas to JSON Schema and Avro formats"
        owner:
          title: Repository Owner
          type: string
          description: GitHub username or organization
          pattern: '^[a-zA-Z0-9\-_]+$'

    - title: Activity Configuration
      properties:
        packageName:
          title: Go Package Name
          type: string
          description: Go package name for the activity
          default: "xsdschematransform"
        activityName:
          title: Activity Name
          type: string
          description: Display name for the activity
          default: "XSD Schema Transform"
        version:
          title: Activity Version
          type: string
          description: Version of the activity
          default: "1.0.0"
        defaultOutputFormat:
          title: Default Output Format
          type: string
          description: Default schema output format
          enum:
            - jsonschema
            - avro
            - both
          default: both
        defaultJsonSchemaVersion:
          title: Default JSON Schema Version
          type: string
          description: Default JSON Schema specification version
          enum:
            - draft-04
            - draft-07
            - 2019-09
            - 2020-12
          default: 2020-12
        enableValidation:
          title: Enable Input Validation
          type: boolean
          description: Enable XSD validation by default
          default: false
        includeExamples:
          title: Include Examples
          type: boolean
          description: Include example values in generated schemas by default
          default: false

  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          packageName: ${{ parameters.packageName }}
          activityName: ${{ parameters.activityName }}
          version: ${{ parameters.version }}
          defaultOutputFormat: ${{ parameters.defaultOutputFormat }}
          defaultJsonSchemaVersion: ${{ parameters.defaultJsonSchemaVersion }}
          enableValidation: ${{ parameters.enableValidation }}
          includeExamples: ${{ parameters.includeExamples }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.name }}
        defaultBranch: main

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}