site_name: Server-Sent Events (SSE) Connector
site_description: Real-time data streaming connector with unified trigger and activity

nav:
  - Home: index.md

theme:
  name: material
  palette:
    primary: blue
    accent: blue

docs_dir: docs
site_dir: site

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true