site_name: Server-Sent Events Connector
site_description: Real-time streaming communication with Server-Sent Events protocol

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
