apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: flogo-connector-sse
  title: Server-Sent Events (SSE) Connector
  description: Real-time data streaming connector with unified trigger and activity for server-sent events, dashboards, and live notifications
  tags:
    - flogo
    - connector
    - sse
    - server-sent-events
    - real-time
    - streaming
    - dashboard
    - notifications
    - web-integration
spec:
  owner: flogo-team
  type: flogo-connector
  parameters:
    - title: Connector Information
      required:
        - connector_name
        - namespace
      properties:
        connector_name:
          title: Connector Name
          type: string
          description: Name for your SSE connector instance
          pattern: '^[a-zA-Z][a-zA-Z0-9_-]*$'
          default: sse-connector
        namespace:
          title: Namespace
          type: string
          description: Namespace for the connector (e.g., com.company.project)
          pattern: '^[a-zA-Z][a-zA-Z0-9_.]*$'
          default: com.example

    - title: Server Configuration
      properties:
        default_port:
          title: Default Server Port
          type: integer
          description: Default port for the SSE server
          minimum: 1024
          maximum: 65535
          default: 9998
        default_path:
          title: Default Server Path
          type: string
          description: Default HTTP path for SSE endpoint
          pattern: '^/[a-zA-Z0-9/_-]*$'
          default: /events
        max_connections:
          title: Maximum Connections
          type: integer
          description: Maximum concurrent client connections
          minimum: 1
          maximum: 10000
          default: 1000
        enable_cors:
          title: Enable CORS
          type: boolean
          description: Enable Cross-Origin Resource Sharing for web applications
          default: true

    - title: Event Management
      properties:
        enable_event_store:
          title: Enable Event Store
          type: boolean
          description: Enable event buffering and replay for client reconnections
          default: true
        event_store_size:
          title: Event Store Size
          type: integer
          description: Maximum number of events to store for replay
          minimum: 0
          maximum: 100000
          default: 1000
        event_ttl_seconds:
          title: Event TTL (seconds)
          type: integer
          description: Time-to-live for stored events in seconds
          minimum: 1
          maximum: 86400
          default: 3600
        keep_alive_interval:
          title: Keep-Alive Interval (seconds)
          type: integer
          description: Interval for sending keep-alive messages to clients
          minimum: 1
          maximum: 300
          default: 30

    - title: Advanced Features
      properties:
        support_topics:
          title: Support Topic-Based Delivery
          type: boolean
          description: Enable topic-based event filtering and delivery
          default: true
        enable_connection_metrics:
          title: Enable Connection Metrics
          type: boolean
          description: Track connection statistics and performance metrics
          default: true
        enable_graceful_shutdown:
          title: Enable Graceful Shutdown
          type: boolean
          description: Properly close connections during server shutdown
          default: true
        custom_headers:
          title: Custom HTTP Headers
          type: boolean
          description: Support for custom HTTP headers in responses
          default: false

    - title: Security & Performance
      properties:
        connection_timeout:
          title: Connection Timeout (seconds)
          type: integer
          description: Timeout for idle client connections
          minimum: 10
          maximum: 3600
          default: 300
        enable_rate_limiting:
          title: Enable Rate Limiting
          type: boolean
          description: Enable rate limiting for event broadcasting
          default: false
        buffer_size:
          title: Buffer Size (bytes)
          type: integer
          description: Buffer size for event data
          minimum: 1024
          maximum: 1048576
          default: 8192
        enable_compression:
          title: Enable Compression
          type: boolean
          description: Enable gzip compression for event data
          default: false

    - title: Repository Information
      required:
        - repo_name
      properties:
        repo_name:
          title: Repository Name
          type: string
          description: Name of the repository to create
          pattern: '^[a-zA-Z][a-zA-Z0-9_-]*$'
        description:
          title: Description
          type: string
          description: A brief description of your SSE connector
          default: Server-Sent Events connector for real-time data streaming and live notifications

  steps:
    - id: fetch-base
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          connector_name: ${{ parameters.connector_name }}
          namespace: ${{ parameters.namespace }}
          default_port: ${{ parameters.default_port }}
          default_path: ${{ parameters.default_path }}
          max_connections: ${{ parameters.max_connections }}
          enable_cors: ${{ parameters.enable_cors }}
          enable_event_store: ${{ parameters.enable_event_store }}
          event_store_size: ${{ parameters.event_store_size }}
          event_ttl_seconds: ${{ parameters.event_ttl_seconds }}
          keep_alive_interval: ${{ parameters.keep_alive_interval }}
          support_topics: ${{ parameters.support_topics }}
          enable_connection_metrics: ${{ parameters.enable_connection_metrics }}
          enable_graceful_shutdown: ${{ parameters.enable_graceful_shutdown }}
          custom_headers: ${{ parameters.custom_headers }}
          connection_timeout: ${{ parameters.connection_timeout }}
          enable_rate_limiting: ${{ parameters.enable_rate_limiting }}
          buffer_size: ${{ parameters.buffer_size }}
          enable_compression: ${{ parameters.enable_compression }}
          repo_name: ${{ parameters.repo_name }}
          description: ${{ parameters.description }}

    - id: publish
      name: Publish to Repository
      action: publish:github
      input:
        repoUrl: github.com?repo=${{ parameters.repo_name }}
        description: ${{ parameters.description }}
        defaultBranch: main
        gitCommitMessage: 'Initial commit: SSE Connector'

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}