site_name: BWCE Jenkins CI/CD Pipeline
site_description: This TIBCO BusinessWorks Container Edition (BWCE) template provides a robust solution for implementing CI/CD pipelines using Jenkins. It demonstrates best practices for automating the build, test, and deployment processes for BWCE applications.

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site