apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mp-entry-bwce-cicd-pipeline
  title: BWCE CI/CD Pipeline Template
  description: Comprehensive CI/CD pipeline template for TIBCO BusinessWorks Container Edition applications. Includes Jenkins pipeline configuration, Docker containerization, Kubernetes deployment, automated testing, monitoring, and best practices for enterprise integration applications.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tibco.developer.hub/marketplace:
    isNew: true
    popularity: 8
    isMultiInstall: false
    imageURL: ""
    moreInfo:
      - text: TIBCO BusinessWorks Documentation
        url: https://docs.tibco.com/products/tibco-businessworks-container-edition
        icon: docs
      - text: Jenkins Pipeline Documentation
        url: https://jenkins.io/doc/book/pipeline/
        icon: docs
      - text: Kubernetes Deployment Guide
        url: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
        icon: kubernetes
      - text: Docker Best Practices
        url: https://docs.docker.com/develop/dev-best-practices/
        icon: docker
      - text: Source Repository
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/tree/main/bwce/templates/cicd-jenkins
        icon: github
  tags:
    - devhub-marketplace
    - bwce
    - cicd
    - jenkins
    - automation
spec:
  owner: tibco-integration-team
  type: template
  presentation:
    buttonLabels:
      createButtonText: Install CI/CD Template
  parameters:
    - title: Accept the Marketplace Entry
      required:
        - accept
      properties:
        description:
          type: "null"
          description: |
            ## Install BWCE CI/CD Pipeline Template into your TIBCO Developer Hub

            **Description:** Comprehensive CI/CD pipeline setup for TIBCO BusinessWorks Container Edition applications with Jenkins, Docker, and Kubernetes integration.

            **What You'll Get:** Complete CI/CD pipeline template with Jenkins configuration, Docker containerization, Kubernetes deployment, and monitoring setup for BWCE applications.

            Each item made available to you in the TIBCO® Developer Hub Marketplace is subject to its own individual license. This item is subject to the following [license](https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/LICENSE).

            **By accessing or using this item, you agree to assume full responsibility for its proper use and compliance with all applicable license terms.**
        accept:
          title: I Agree
          type: boolean
          default: false
  steps:
    - id: registerItem
      name: Installing Marketplace Entry...
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/bwce/templates/cicd-jenkins/catalog-info.yaml

  output:
    links:
      - title: Open in catalog
        type: catalog
        icon: catalog
        entityRef: ${{ steps.registerItem.output.entityRef }}
      - title: Documentation
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/bwce/templates/cicd-jenkins/docs/index.md
        icon: docs
      - title: Back to Marketplace
        icon: dashboard
        url: /marketplace