site_name: AWS Signature V4 Activity
site_description: AWS Signature Version 4 authentication activity for secure AWS API calls

nav:
  - Introduction: index.md

plugins:
  - techdocs-core

docs_dir: docs
site_dir: site

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true