apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mp-entry-flogo-activity-awssignaturev4
  title: AWS Signature V4 Generator Activity
  description: Generate AWS Signature Version 4 authentication headers for secure REST API calls to AWS services
  annotations:
    backstage.io/techdocs-ref: dir:.
  tibco.developer.hub/marketplace:
    isNew: true
    popularity: 8
    isMultiInstall: true
    imageURL: ""
    moreInfo:
      - text: Source Repository
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/tree/main/flogo/extensions/activity/awssignaturev4
        icon: github
      - text: Documentation
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/flogo/extensions/activity/awssignaturev4/docs/index.md
        icon: docs
  tags:
    - devhub-marketplace
    - flogo
    - activity
    - aws
    - signature-v4
    - authentication
    - security
spec:
  owner: tibco-flogo-team
  type: service
  presentation:
    buttonLabels:
      createButtonText: Install Activity
  parameters:
    - title: Accept the Marketplace Entry
      required:
        - accept
      properties:
        description:
          type: "null"
          description: |
            ## Install AWS Signature V4 Generator Activity into your TIBCO Developer Hub

            **Description:** Complete AWS Signature Version 4 implementation for authenticating REST API calls to AWS services. Supports all AWS services with multi-service compatibility, session tokens, and comprehensive debugging.

            **What You'll Get:** 
            - Complete AWS Signature V4 authentication implementation
            - Multi-service support (S3, SQS, DynamoDB, Lambda, EC2, etc.)
            - Session token support for temporary credentials from AWS STS
            - Custom headers support with signature calculation
            - Comprehensive input validation with detailed error messages
            - Debug outputs including canonical request and string-to-sign

            Each item made available to you in the TIBCO® Developer Hub Marketplace is subject to its own individual license. This item is subject to the following [license](https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/LICENSE).

            **By accessing or using this item, you agree to assume full responsibility for its proper use and compliance with all applicable license terms.**
        accept:
          title: I Agree
          type: boolean
          default: false
  steps:
    - id: registerItem
      name: Installing Marketplace Entry...
      action: catalog:register
      input:
        catalogInfoUrl: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/flogo/extensions/activity/awssignaturev4/catalog-info.yaml

  output:
    links:
      - title: Open in catalog
        type: catalog
        icon: catalog
        entityRef: ${{ steps.registerItem.output.entityRef }}
      - title: Documentation
        url: https://github.com/mpandav-tibco/tib-devhub-hackathon/blob/main/flogo/extensions/activity/awssignaturev4/docs/index.md
        icon: docs
      - title: Back to Marketplace
        icon: dashboard
        url: /marketplace
    awsServices: ["S3", "SQS", "DynamoDB", "Lambda", "EC2", "CloudWatch", "SNS", "SES"]